AWSTemplateFormatVersion: '2010-09-09'
Description: Creates the Lambda function and API for the PyTorch inference application.
Globals:
  Function:
    Timeout: 30
Outputs:
  PyTorchApi:
    Description: API Gateway endpoint URL for Prod stage for PyTorch function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/invocations/
  PyTorchFunction:
    Description: PyTorch Lambda Function ARN
    Value:
      Fn::GetAtt:
      - PyTorchFunction
      - Arn
  PyTorchFunctionIamRole:
    Description: Implicit IAM Role created for PyTorch function
    Value:
      Fn::GetAtt:
      - PyTorchFunctionRole
      - Arn
Parameters:
  BucketName:
    Default: somebucket
    Description: Enter the name of the S3 bucket storing your PyTorch model artefacts.
    Type: String
  LambdaLayerArn:
    Default: arn:aws:lambda:us-east-1:934676248949:layer:pytorchv1-py36:2
    Description: Enter the PyTorch Lambda Layer ARN. Defaults to a public one in the
      "us-east-1" region.
    Type: String
  ObjectKey:
    Default: somekey
    Description: Enter the S3 object key path of your PyTorch model artefacts.
    Type: String
Resources:
  PyTorchFunction:
    Properties:
      CodeUri: s3://serverless-ssd300-vgg/ad007979efd975fe9695c2861cd3b0ac
      Environment:
        Variables:
          MODEL_BUCKET:
            Ref: BucketName
          MODEL_KEY:
            Ref: ObjectKey
      Events:
        PyTorch:
          Properties:
            Method: post
            Path: /invocations
          Type: Api
      Handler: app.lambda_handler
      Layers:
      - Ref: LambdaLayerArn
      MemorySize: 2048
      Policies:
      - S3ReadPolicy:
          BucketName:
            Ref: BucketName
      Runtime: python3.6
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
